name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$GCP_SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H $GCP_SSH_HOST >> ~/.ssh/known_hosts
        env:
          GCP_SSH_KEY: ${{ secrets.GCP_SSH_KEY }}
          GCP_SSH_HOST: ${{ secrets.GCP_SSH_HOST }}

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no $GCP_SSH_USER@$GCP_SSH_HOST "bash ~/deploy.sh"
        env:
          GCP_SSH_USER: ${{ secrets.GCP_SSH_USER }}
          GCP_SSH_HOST: ${{ secrets.GCP_SSH_HOST }}
